services:
  - type: web
    name: marketplace-backend
    runtime: node
    buildCommand: |
      cd /opt/render/project/src/backend
      npm install
      npm run build  # Si necesitas construcción adicional
    startCommand: |
      cd /opt/render/project/src/backend
      node --experimental-specifier-resolution=node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_URL
        fromDatabase:
          name: marketplace-db
          property: connectionString

  - type: pg
    name: marketplace-db
    plan: free