services:
  - type: web
    name: node-backend-market
    runtime: node
    buildCommand: |
      cd /opt/render/project/src/backend
      npm install
    startCommand: |
      cd /opt/render/project/src/backend
      node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: postgres-db-market
          property: connectionString

  - type: pg
    name: postgres-db-market
    plan: free