services:
  # Backend Service
  - type: web
    name: node-backend-market
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: postgres-db-market
          property: connectionString

  # PostgreSQL Database
  - type: pg
    name: postgres-db-market
    plan: free